name: Build & Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AUTH_MODE: "none"
    APP_MODE: "ci"
    CI: true

jobs:
    frontend-ci:
        uses: DCC-BS/ci-workflows/.github/workflows/ci.yml@2bfad28c27c02b4fe13dbadeb2b8ae970b2fae15
